//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.BetterDirectoryListing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMS.BetterDirectoryListing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $(document).ready(function(){
        ///			$(&apos;#DirectoryListing&apos;).DataTable({
        ///				&quot;paging&quot;: false,
        ///				&quot;fixedHeader&quot;: {
        ///					&quot;header&quot;:true
        ///				}
        ///			});
        ///		});.
        /// </summary>
        internal static string inlineScriptAtEnd {
            get {
                return ResourceManager.GetString("inlineScriptAtEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a { text-decoration: none; }
        ///a:hover { text-decoration: underline; }
        ///p { font-family: verdana; font-size: 10pt; }
        ///h2 { font-family: verdana; margin: 0px; }
        ///table { width: 800px; text-align: left; margin-left: 0px; border: 0px; }
        ///td { font-family: verdana; font-size: 10pt; }
        ///th:nth-child(odd), td:nth-child(odd) { background-color: #f9f9f9; }
        ///td { border-top: 1pt solid #dddddd; }
        ///th { border-top: 1pt solid #dddddd; }
        ///th:first-child, td:first-child { border-left: 1pt solid #dddddd; }
        ///th:last-child, t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string inlineStyleInHead {
            get {
                return ResourceManager.GetString("inlineStyleInHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;asp:Repeater ID=&quot;DirectoryListing&quot; runat=&quot;server&quot; EnableViewState=&quot;False&quot;&gt;
        ///			&lt;HeaderTemplate&gt;
        ///				&lt;table id=&quot;DirectoryListing&quot; style=&quot;width: 100%&quot;&gt;
        ///					&lt;thead&gt;
        ///						&lt;tr&gt;
        ///							&lt;th&gt;Name&lt;/th&gt;
        ///							&lt;th&gt;Created&lt;/th&gt;
        ///							&lt;th&gt;Last Modified&lt;/th&gt;
        ///							&lt;th&gt;Size&lt;/th&gt;
        ///						&lt;/tr&gt;
        ///					&lt;/thead&gt;
        ///						&lt;tbody&gt;
        ///			&lt;/HeaderTemplate&gt;
        ///			&lt;ItemTemplate&gt;
        ///				&lt;tr&gt;
        ///					&lt;td&gt;
        ///						&lt;i class=&quot;far fa-&lt;%# GetFileIconCss(Path.GetExtension(((ListEntry)Container.DataItem).Path)) %&gt;&quot;&gt;&lt;/i&gt;
        ///						&lt;a href=&quot;&lt;%#  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rptMain {
            get {
                return ResourceManager.GetString("rptMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;i class=&quot;fa fa-level-up-alt&quot; /&gt; To Parent Directory.
        /// </summary>
        internal static string toParentDirectory {
            get {
                return ResourceManager.GetString("toParentDirectory", resourceCulture);
            }
        }
    }
}
